services:
  # === BACKEND (Express + Prisma + SQLite) ===
  - type: web
    name: shift-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: |
      npm install
      npm run prisma:generate
      npm run prisma:migrate
      npm run build
    startCommand: npm run start
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/var/data/dev.db

  # === FRONTEND (Vite static site) ===
  - type: static
    name: shift-frontend
    rootDir: frontend
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: dist
    envVars:
      # VITE_API_BASE będzie automatycznie wskazywać publiczny URL backendu
      - key: VITE_API_BASE
        fromService:
          name: shift-api
          type: web
          property: url
      # (opcjonalne brandowanie)
      - key: VITE_PROJECT_TITLE
        value: SHIFT - Digital Readiness Assessment
