services:
  - type: web
    name: shift-api
    runtime: node
    plan: free         # <= darmowa instancja
    rootDir: backend
    buildCommand: |
      npm install
      npm run prisma:generate
      npm run build
    preDeployCommand: npm run prisma:migrate
    startCommand: npm run start
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/var/data/dev.db

  - type: web
    name: shift-frontend
    runtime: static
    rootDir: frontend
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./dist
