services:
  - type: web
    name: shift-api
    env: node
    rootDir: backend
    buildCommand: |
      npm install
      npm run prisma:generate
      npm run prisma:migrate
      npm run build
    startCommand: npm run start
    autoDeploy: true
    disk:                # <-- POJEDYNCZE 'disk', nie 'disks'
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/var/data/dev.db

staticSites:
  - name: shift-frontend
    rootDir: frontend
    buildCommand: |
      npm install
      npm run build
    publishPath: dist
    # jeśli trzeba, dodasz ręcznie VITE_API_BASE w UI po pierwszym deployu


